### ISSUE TITLE
using yum to find out Satellite version, cause pulling 2 versions (1 for installed, and the other one for available)

### ISSUE THREAD

**Issue by glimpsovstar** [talorh/satellite-backup#1]
My satellite backup started to fail, due to unknown satellite version.

variable output was;
+ SAT_VER='6.3
6.3'

When I ran yum info satellite, I saw why.

[root@hostname satellite_backup]# yum info satellite
Loaded plugins: langpacks, product-id, search-disabled-repos, subscription-
              : manager
**Installed Packages**
Name        : satellite
Arch        : noarch
**Version     : 6.3.0**
Release     : 23.0.el7sat
Size        : 0.0
Repo        : installed
From repo   : rhel-7-server-satellite-6.3-rpms
Summary     : A package for managing application life-cycle for Linux systems
URL         : https://access.redhat.com/products/red-hat-satellite
License     : GPLv2
Description : Provides a package for managing application life-cycle for Linux
            : systems.

**Available Packages**
Name        : satellite
Arch        : noarch
**Version     : 6.3.0.1**
Release     : 1.el7sat
Size        : 7.8 k
Repo        : rhel-7-server-satellite-6.3-rpms/x86_64
Summary     : A package for managing application life-cycle for Linux systems
URL         : https://access.redhat.com/products/red-hat-satellite
License     : GPLv2
Description : Provides a package for managing application life-cycle for Linux
            : systems.

[root@hostname satellite_backup]# yum info satellite |grep Version
Version     : 6.3.0
Version     : 6.3.0.1

I thought it would be better to use "rpm" command to query rather than yum this time.

**Comment by talorh** [comment]
This has been fixed.

Working it out like this instead:

rpm -q satellite |awk -F - '{print $2}' |cut -c 1-3
